version: '3.9'

services:
  postgres:
    image: postgres:11
    container_name: postgres
    ports:
      - "$PGPORT:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - my_dbdata:/var/lib/postgresql/data
    restart: always

volumes:
  my_dbdata: